from typing import Any

# Supabase no longer exposes OpenAPI metadata through publishable keys. This catalog is
# intentionally explicit: each resource and column below was verified against the public API.
IPL_SCHEMA_CATALOG: tuple[dict[str, Any], ...] = (
    {
        "name": "matches",
        "description": "One row per IPL match, including teams, venue, toss, result, and status.",
        "primary_key": ["match_id"],
        "columns": [
            ("match_id", "text", False, "Unique match identifier"),
            ("season_year", "integer", False, "IPL season year"),
            ("data_source", "text", True, "Origin of the match record"),
            ("source_url", "text", True, "Source dataset URL"),
            ("match_number", "text", True, "Match number or stage label"),
            ("match_date", "date", False, "Scheduled match date"),
            ("start_time", "time", True, "Scheduled start time"),
            ("status", "text", False, "Match status"),
            ("home_team_id", "text", False, "Home team identifier"),
            ("home_team_name", "text", False, "Home team display name"),
            ("away_team_id", "text", False, "Away team identifier"),
            ("away_team_name", "text", False, "Away team display name"),
            ("venue", "text", True, "Match venue"),
            ("city", "text", True, "Venue city"),
            ("result_text", "text", True, "Human-readable result"),
            ("winner_team_id", "text", True, "Winning team identifier"),
            ("toss_winner", "text", True, "Team that won the toss"),
            ("toss_decision", "text", True, "Bat or field decision"),
            ("target", "text", True, "Target score when available"),
            ("current_innings", "integer", True, "Current or final innings number"),
            ("details_loaded", "boolean", False, "Whether detailed records are loaded"),
            ("updated_at", "timestamp", False, "Last source update"),
        ],
    },
    {
        "name": "players",
        "description": "IPL player directory with the seasons in which each player appears.",
        "primary_key": ["player_id"],
        "columns": [
            ("player_id", "text", False, "Unique player identifier"),
            ("player_name", "text", False, "Player name"),
            ("player_short_name", "text", True, "Short display name"),
            ("image_url", "text", True, "Player image URL"),
            ("first_seen_season", "integer", False, "First IPL season in the dataset"),
            ("last_seen_season", "integer", False, "Latest IPL season in the dataset"),
        ],
    },
    {
        "name": "innings",
        "description": "Innings-level totals and batting/bowling teams for each match.",
        "primary_key": ["match_id", "innings_number"],
        "columns": [
            ("match_id", "text", False, "Related match identifier"),
            ("innings_number", "integer", False, "Innings number"),
            ("batting_team_id", "text", False, "Batting team identifier"),
            ("batting_team_name", "text", False, "Batting team display name"),
            ("bowling_team_id", "text", False, "Bowling team identifier"),
            ("bowling_team_name", "text", False, "Bowling team display name"),
            ("runs", "integer", False, "Total innings runs"),
            ("wickets", "integer", False, "Wickets lost"),
            ("overs", "text", False, "Overs completed using cricket notation"),
            ("extras", "integer", False, "Total extra runs"),
            ("status", "text", False, "Innings status"),
        ],
    },
    {
        "name": "batting_stats",
        "description": "Pre-aggregated IPL batting totals per season, team, and batter.",
        "primary_key": ["season_year", "batting_team_id", "batter_id"],
        "columns": [
            ("season_year", "integer", False, "IPL season year"),
            ("batting_team_id", "text", False, "Team identifier for which the batter played"),
            ("batting_team_name", "text", False, "Team for which the batter scored these runs"),
            ("batter_id", "text", False, "Batter player identifier"),
            ("batter_name", "text", False, "Batter display name"),
            ("runs", "integer", False, "Total individual batting runs"),
            ("matches", "integer", False, "Matches in which the batter faced a delivery"),
            ("fours", "integer", False, "Total fours hit"),
            ("sixes", "integer", False, "Total sixes hit"),
        ],
    },
    {
        "name": "bowling_stats",
        "description": "Pre-aggregated IPL bowling totals per season, team, and bowler.",
        "primary_key": ["season_year", "bowling_team_id", "bowler_id"],
        "columns": [
            ("season_year", "integer", False, "IPL season year"),
            ("bowling_team_id", "text", False, "Team identifier represented by bowler"),
            ("bowling_team_name", "text", False, "Team represented by bowler"),
            ("bowler_id", "text", False, "Bowler player identifier"),
            ("bowler_name", "text", False, "Bowler display name"),
            ("matches", "integer", False, "Matches bowled in"),
            ("legal_balls", "integer", False, "Legal deliveries bowled"),
            ("runs_conceded", "integer", False, "Bowler-attributed runs conceded"),
            ("wickets", "integer", False, "Wickets credited to bowler"),
            ("economy", "numeric", True, "Runs conceded per six legal balls"),
        ],
    },
    {
        "name": "player_match_batting",
        "description": "Per-match IPL batting totals and strike rate for every batter.",
        "primary_key": ["match_id", "innings_number", "batter_id"],
        "columns": [
            ("season_year", "integer", False, "IPL season year"),
            ("match_id", "text", False, "Match identifier"),
            ("match_date", "date", False, "Match date"),
            ("innings_number", "integer", False, "Innings number"),
            ("batting_team_id", "text", False, "Batting team identifier"),
            ("batting_team_name", "text", False, "Team represented by batter"),
            ("opponent_team_id", "text", False, "Opposition team identifier"),
            ("opponent_team_name", "text", False, "Opposition team"),
            ("batter_id", "text", False, "Batter player identifier"),
            ("batter_name", "text", False, "Batter display name"),
            ("runs", "integer", False, "Individual runs in match innings"),
            ("balls_faced", "integer", False, "Deliveries faced excluding wides"),
            ("fours", "integer", False, "Fours hit"),
            ("sixes", "integer", False, "Sixes hit"),
            ("strike_rate", "numeric", True, "Runs per 100 balls"),
        ],
    },
    {
        "name": "player_match_bowling",
        "description": "Per-match IPL bowling figures and economy for every bowler.",
        "primary_key": ["match_id", "innings_number", "bowler_id"],
        "columns": [
            ("season_year", "integer", False, "IPL season year"),
            ("match_id", "text", False, "Match identifier"),
            ("match_date", "date", False, "Match date"),
            ("innings_number", "integer", False, "Innings number"),
            ("bowling_team_id", "text", False, "Bowling team identifier"),
            ("bowling_team_name", "text", False, "Team represented by bowler"),
            ("opponent_team_id", "text", False, "Opposition team identifier"),
            ("opponent_team_name", "text", False, "Opposition team"),
            ("bowler_id", "text", False, "Bowler player identifier"),
            ("bowler_name", "text", False, "Bowler display name"),
            ("legal_balls", "integer", False, "Legal deliveries bowled"),
            ("runs_conceded", "integer", False, "Bowler-attributed runs conceded"),
            ("wickets", "integer", False, "Wickets credited to bowler"),
            ("economy", "numeric", True, "Runs conceded per six legal balls"),
        ],
    },
    {
        "name": "team_season_stats",
        "description": "IPL team match results and win percentage for each season.",
        "primary_key": ["season_year", "team_id"],
        "columns": [
            ("season_year", "integer", False, "IPL season year"),
            ("team_id", "text", False, "Team identifier"),
            ("team_name", "text", False, "Team display name"),
            ("matches_played", "integer", False, "Completed matches"),
            ("wins", "integer", False, "Matches won"),
            ("losses", "integer", False, "Matches lost"),
            ("no_results", "integer", False, "No-result matches"),
            ("ties", "integer", False, "Tied matches"),
            ("win_percentage", "numeric", True, "Wins as percentage of completed matches"),
        ],
    },
    {
        "name": "head_to_head_stats",
        "description": "Season-level IPL results between a canonical pair of teams.",
        "primary_key": ["season_year", "team1_name", "team2_name"],
        "columns": [
            ("season_year", "integer", False, "IPL season year"),
            ("team1_name", "text", False, "Alphabetically first team"),
            ("team2_name", "text", False, "Alphabetically second team"),
            ("matches_played", "integer", False, "Completed meetings"),
            ("team1_wins", "integer", False, "Wins by first team"),
            ("team2_wins", "integer", False, "Wins by second team"),
            ("no_results", "integer", False, "No-result meetings"),
            ("ties", "integer", False, "Tied meetings"),
        ],
    },
    {
        "name": "venue_stats",
        "description": "IPL venue scoring and chasing/defending outcomes by season.",
        "primary_key": ["season_year", "venue", "city"],
        "columns": [
            ("season_year", "integer", False, "IPL season year"),
            ("venue", "text", True, "Venue name"),
            ("city", "text", True, "Venue city"),
            ("matches_played", "integer", False, "Completed matches"),
            ("average_first_innings_runs", "numeric", True, "Average first innings total"),
            ("highest_first_innings_runs", "integer", True, "Highest first innings total"),
            ("batting_first_wins", "integer", False, "Wins by team batting first"),
            ("chasing_wins", "integer", False, "Wins by chasing team"),
            ("no_results", "integer", False, "No-result matches"),
        ],
    },
    {
        "name": "deliveries",
        "description": "Ball-by-ball IPL delivery records, runs, wickets, and participants.",
        "primary_key": ["match_id", "innings_number", "sequence"],
        "columns": [
            ("match_id", "text", False, "Related match identifier"),
            ("innings_number", "integer", False, "Related innings number"),
            ("sequence", "integer", False, "Delivery sequence within the innings"),
            ("over_number", "integer", False, "Zero-based over number"),
            ("ball_number", "integer", False, "Ball number in the over"),
            ("ball_label", "text", False, "Display label such as 0.1"),
            ("batter_id", "text", False, "Striker player identifier"),
            ("batter_name", "text", False, "Striker player name"),
            ("non_striker_id", "text", False, "Non-striker player identifier"),
            ("non_striker_name", "text", False, "Non-striker player name"),
            ("bowler_id", "text", False, "Bowler player identifier"),
            ("bowler_name", "text", False, "Bowler player name"),
            ("batting_runs", "integer", False, "Runs credited to the batter"),
            ("extra_runs", "integer", False, "Extra runs on the delivery"),
            ("total_runs", "integer", False, "Total runs on the delivery"),
            ("extras_type", "text", True, "Type of extra"),
            ("is_wicket", "boolean", False, "Whether a wicket occurred"),
            ("dismissed_player_id", "text", True, "Dismissed player identifier"),
            ("dismissed_player_name", "text", True, "Dismissed player name"),
            ("dismissal_kind", "text", True, "Dismissal type"),
            ("fielder_name", "text", True, "Involved fielder"),
            ("score", "text", True, "Score snapshot"),
            ("commentary", "text", True, "Delivery commentary"),
        ],
    },
    {
        "name": "seasons",
        "description": "Available IPL seasons and their source competition identifiers.",
        "primary_key": ["season_year"],
        "columns": [
            ("season_year", "integer", False, "IPL season year"),
            ("competition_id", "text", False, "Source competition identifier"),
            ("season_id", "text", False, "Source season identifier"),
            ("competition_name", "text", False, "Competition display name"),
            ("feedsource", "text", True, "Dataset feed URL"),
        ],
    },
)

IPL_RELATIONSHIPS: tuple[dict[str, str], ...] = (
    {
        "from_table": "innings",
        "from_column": "match_id",
        "to_table": "matches",
        "to_column": "match_id",
    },
    {
        "from_table": "deliveries",
        "from_column": "match_id",
        "to_table": "matches",
        "to_column": "match_id",
    },
    {
        "from_table": "deliveries",
        "from_column": "batter_id",
        "to_table": "players",
        "to_column": "player_id",
    },
    {
        "from_table": "deliveries",
        "from_column": "non_striker_id",
        "to_table": "players",
        "to_column": "player_id",
    },
    {
        "from_table": "deliveries",
        "from_column": "bowler_id",
        "to_table": "players",
        "to_column": "player_id",
    },
)
